### ISSUE TITLE
Can't click on item frame to open the container

### ISSUE THREAD

**Issue by Bloodlex** [furkanaliunal/ItemFrameToggle#1]
Hey,

After the last update (1.5.0) I'm not able to open containers when clicking on an item frame on it, which was the case on previous versions. Could you please bring back this behavior? Thanks! 🙂

**Comment by furkanaliunal** [comment]
I am going to update as soon as I can. Thank you

**Comment by furkanaliunal** [comment]
Permission checks are now disabled by default. I hope it will meet your need 🌹

**Comment by Bloodlex** [comment]
> Permission checks are now disabled by default. I hope it will meet your need 🌹

Thanks a lot! 👍 🙂

**Comment by furkanaliunal** [comment]
I rewrited the permissions checks. I am going to release new version when I added commands too
